ensdomains/ens-app-v3

src/components/@molecules/SearchInput/SearchResults.tsx

this is a stupid css hack, however, it works.

fix numbers in search box

---

public/locales/en/profile.json
src/components/@molecules/ErrorContainer.tsx
src/hooks/useNameDetails.tsx
src/hooks/useRegistrationStatus.ts
src/layouts/Content.tsx

- names cannot yet be registered, renewed, or imported in v3
- this PR adds a warning link to v2 for any state that isn't yet supported

Add link to v2 for unsupported name states

---

src/hooks/useAvatar.ts

- changes useAvatar and useNFTImage to create a invisible img element
- fixes load issue with object URIs

Fix avatar load

---

src/components/pages/profile/[name]/details/SubnamesTab.tsx
src/components/pages/profile/[name]/details/details.test.tsx
src/hooks/useSubnamePagination.test.ts
src/hooks/useSubnamePagination.ts
src/pages/my/names.tsx
src/pages/profile/details.tsx

- removed grid view option from my names page
- refactored subname pagination so that all pagination uses large queries to streamline API
- added subname page to URL query

remove grid view + refactor subname pagination

---

README.md

- uses pnpm references instead of yarn
- adds more test environment details

fix: update readme to include test environment details

---

src/components/@atoms/CheckButton/CheckButton.tsx
src/components/@molecules/NameTableHeader/NameTableHeader.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarCrop.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarScrollBox.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarViewManager.tsx
src/components/ProfileSnippet.tsx
src/components/pages/profile/NameSnippetMobile.tsx
src/components/pages/profile/[name]/details/AdvancedTab/AdvancedTab.tsx
src/layouts/Content.tsx
src/layouts/ContentGrid.tsx
src/pages/my/names.tsx

- fixed no names message during names page load
- added hover states for buttons on names page
- removed weird looking expiry box on mobile
- fixed name from overflowing weirdly on profile page
- removed registration date when name is not 2ld .eth in more tab
- fix avatar crop usability issues

Misc fixes

---

e2e/specs/stateless/08_registerName.spec.js
src/components/pages/profile/settings/TransactionSection.test.tsx
src/components/pages/profile/settings/TransactionSection.tsx

Also added more info for items to do with registering names

"Start timer" tx does not always show up in settings

---

public/locales/en/common.json
public/locales/en/profile.json
public/locales/en/transactionFlow.json
src/components/@molecules/TransactionDialogManager/stage/Intro.tsx
src/components/pages/profile/[name]/tabs/MoreTab/MoreTab.tsx
src/components/pages/profile/[name]/tabs/MoreTab/Ownership.tsx
src/hooks/useDNSProof.ts
src/transaction-flow/intro/SyncManager.tsx
src/transaction-flow/intro/index.ts
src/transaction-flow/transaction/index.ts
src/transaction-flow/transaction/syncManager.ts

synced = DNS owner and manager are the same value
if synced, no extra information will show
if not synced and connected address is DNS owner, will show button to sync manager and allow manager syncing
if not synced and connected address is manager, will show warning that the DNS owner can change the manager at any time
for now may want to test manually (i need to sort out DNSSEC in the test env soon)

feat: add "Sync manager" option for DNS names

---

src/components/@molecules/FaucetBanner.tsx
src/hooks/useFaucet.ts
src/pages/index.tsx
src/types/index.ts

- banner displayed on homepage
- connect with any wallet that is yet to claim and it will show banner
- clicking banner shows dialog which allows claiming
- paired with cloudflare worker - not yet on github

feat: goerli faucet functionality

---

src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx
src/pages/profile.tsx

- strip debug info from error message
- fix registration page flash when clicking view profile after registering a name

fix: misc fixes

---

.github/workflows/pages-deployment.yaml
functions/_middleware.ts
generate-site-map.mjs

- disabled site map in workflow since we are using goerli
- fixed cf middleware for static files
- fixed site map generation script

fix: misc for main branch deploy

---

jest.config.js
package.json
pnpm-lock.yaml
public/locales/en/common.json
src/components/@molecules/ProfileEditor/Avatar/AvatarCrop.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarScrollBox.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarUpload.test.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarViewManager.tsx
src/components/@molecules/SearchInput/SearchInput.tsx
src/components/@molecules/SearchInput/SearchResult.tsx
src/components/AvatarWithZorb.tsx
src/components/ProfileSnippet.tsx
src/components/pages/profile/ProfileDetails.tsx
src/components/pages/profile/[name]/registration/steps/Complete.tsx
src/components/pages/profile/settings/PrimarySection.tsx
src/hooks/useAvatar.ts
src/hooks/useBasicName.ts
src/layouts/Basic.tsx
src/utils/avatarUpload.test.ts
src/utils/avatarUpload.ts
src/utils/registrationStatus.test.ts
src/utils/registrationStatus.ts

fixed:
- ipad/safari footer is not aligned with bottom of page (stupid workaround, i shouldn't need to do this)
- extra horizontal line on profile card after disconnecting (mobile)
- ios/safari search input focus on click with keyboard
- "Not Supported" flash in search for DNS names
- use "Imported" for dns names in search instead of "Registered"
- use "Owned" for subnames in search instead of "Registered"
- avatars reloading too frequently
- avatar uploader scrollbars/buggy/non-centred images

fix: misc bugs 5

---

src/utils/analytics.ts

Added a few console.log for debugging as it seems not firing an event to plausible

Add some debugging message and remove production

---

src/components/ProfileSnippet.tsx
src/components/pages/profile/[name]/tabs/ProfileTab.tsx
src/hooks/useBasicName.ts
src/hooks/useValidate.test.ts
src/hooks/useValidate.ts

can test at path `/🔥❤🔥.eth/expired-profile`
message should show immediately on page load

fix: non-ascii message flash

---

src/components/@molecules/SearchInput/SearchInput.test.tsx
src/components/@molecules/SearchInput/SearchInput.tsx
src/components/@molecules/SearchInput/types.ts

to test: search for some names/addresses and click on them
search history should be in last searched order now (recent first)

fix: search history order

---

src/components/@molecules/ProfileEditor/Avatar/AvatarCrop.tsx
src/utils/avatarUpload.ts

fix: avatar crop snapping

---

public/locales/en/dnssec.json
public/locales/nl/dnssec.json
public/locales/zh/dnssec.json
src/components/pages/import/[name]/AddTextRecord.tsx
src/components/pages/import/[name]/EnableDNSSEC.tsx

Added link and instructions for enabling DNSSEC on Cloudflare hosted domains.

Added Cloudflare instructions to DNSSEC wizard

---

public/locales/en/register.json
public/locales/en/transactionFlow.json
public/locales/nl/transactionFlow.json
public/locales/zh/register.json
public/locales/zh/transactionFlow.json

- changed primary name message during registration
- changed timer/commit message during registration
- changed some input examples
ref: FET-697

chore: small copy tweaks

---

jest.config.js
src/components/pages/profile/ProfileDetails.test.tsx
src/components/pages/profile/ProfileDetails.tsx
src/hooks/useBasicName.test.ts
src/hooks/useBasicName.ts
src/hooks/useDNSOwner.ts
src/hooks/useNameDetails.tsx
src/hooks/useSubnameInfiniteQuery.ts
src/hooks/useSupportsTLD.ts
src/hooks/useZorb.ts
src/utils/gradient.ts

- root name page now works (is on the /tlds route but we will have to live with that for now)
- on real TLD pages, will show [root] as parent
- added custom avatar on root page
Fixes FET-1063

fix: support [root] name + show as parent on tlds

---

src/components/@molecules/TransactionDialogManager/DisplayItems.tsx
src/components/pages/profile/[name]/registration/steps/Profile/AddProfileRecordView.test.tsx
src/constants/supportedOtherRecordKeys.json
src/hooks/useProfileEditorForm.test.ts
src/transaction-flow/input/RevokePermissions/RevokePermissions-flow.tsx
src/transaction-flow/input/RevokePermissions/RevokePermissions.test.tsx
src/transaction-flow/input/RevokePermissions/views/SetExpiryView.tsx
src/utils/datetime-local.ts

Fixes FET-1040, FET-1030, and FET-916
also removed milliseconds from the expiry selection when revoking permissions (since it isn't set on chain).

fix: misc bugs 8

---

package.json
pnpm-lock.yaml
public/locales/en/error.json
src/components/@atoms/ErrorScreen.tsx
src/layouts/Basic.tsx
src/pages/404.tsx

- custom 404 error page (e.g. with /[name]/djkfdskjfjkdfjk)
- custom application error page (you will have to manually throw an exception in a component to test)
Fixes FET-946

feat: custom error page + application error

---

package.json
pnpm-lock.yaml
src/components/pages/profile/[name]/registration/steps/Profile/profileRecordUtils.test.ts
src/components/pages/profile/[name]/registration/steps/Profile/profileRecordUtils.ts
src/hooks/useBasicName.test.ts

requires this ensjs pr: https://github.com/ensdomains/ensjs-v3/pull/126
with that pr, ensjs supports setting address records to empty values, meaning we no longer need to feed empty address to delete an address record.
Fixes FET-1044

fix: use empty value when deleting address record

---

e2e/specs/stateful/01_address.spec.js
e2e/specs/stateful/02_profile.spec.js
e2e/specs/stateful/03_dnsclaim.spec.js
e2e/specs/stateless/02_setPrimary.spec.js
src/components/pages/profile/[name]/tabs/MoreTab/Ownership.tsx

changes:
- minor fixes in more tab for dns reclaim code
- rewrote address/profile to use a `cy.visit()` in each `it()`
Fixes FET-1069

fix: stateful tests

---

package.json
pnpm-lock.yaml

chore: bump ensjs

---

package.json
pnpm-lock.yaml
src/components/pages/import/[name]/AddTextRecord.tsx
src/components/pages/import/[name]/EnableDNSSEC.tsx
src/components/pages/import/[name]/shared.tsx
src/components/pages/profile/ProfileButton.tsx

changes:
- removed `target="_blank"` for ownership links on profile
- use scrollable dropdowns in dnssec claim flow
- profile dropdown width fix propagated from thorin
Fixes FET-1075, FET-1062, and FET-1039

fix: fixes from thorin

---

src/test-utils.tsx
src/transaction-flow/input/ExtendNames/ExntedNames-flow.test.tsx
src/transaction-flow/input/ExtendNames/ExtendNames-flow.tsx

Friendlier loading states when extending name

---

src/hooks/useEstimateRegistration.ts

halved registration gas estimate, it was still using maxFeePerGas

fix: registration gas estimate

---

package.json
pnpm-lock.yaml

Fet 1106 names list normalisation error

---

package.json
pnpm-lock.yaml
src/components/@atoms/RouteItem/RouteItem.tsx
src/components/ConnectButton.tsx
src/components/TabBar.tsx
src/hooks/transactions/useHasPendingTransactions.ts

changes:
- bumped thorin
- added indicator dot to settings button under profile dropdown when pending txs (desktop)
- using thorin indicator dot functionality
- added indicator dot to settings button under profile slideout on tab menu when pending txs (mobile)
- custom component but also uses thorin indicator dot functionality
Fixes FET-1053

feat: re-add transaction indicator dot

---

src/hooks/useBasicName.ts
src/test-utils.tsx
src/utils/cacheKeyFactory.ts

Update cache keys

---

.github/workflows/pages-deployment.yaml
package.json
scripts/generate-site-map.mjs

changes:
- re-enable sitemap generation in pages deployment action
- move script file to /scripts/
- remove `/profile/` prefix from profile urls

fix: enable sitemaps generator script

---

next.config.js

fixes links while running in dev mode
changes:
- only generate metamask bundle when building

fix: dev server

---

src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx

changes:
- removed commit gas addition in registration
- set gas fee to 0 in estimate, so no out of balance error if user has enough eth for value of tx
Fixes FET-1212

fix: gas estimate tweaks

---

src/hooks/useAdvancedEditor.ts
src/transaction-flow/input/AdvancedEditor/AdvancedEditor.test.tsx

changes:
- added match for empty abi field in advanced editor hook
Fixes FET-1142

fix: allow removing abi in advanced editor

---

src/components/pages/profile/[name]/registration/steps/Pricing/TemporaryPremium.tsx

changes:
- tweaked hover dot location
- target price input is now only formatted on blur, so when user is entering values nothing is changed
Fixes FET-1218

fix: premium chart target price input

---

public/locales/en/common.json
src/components/ProfileSnippet.tsx
src/components/pages/profile/[name]/tabs/ProfileTab.tsx

changes:
- isPrimary prop in profile snippet
- primary name tag shown for primary name
Fixes FET-1216

feat: primary name tag in snippet

---

src/components/pages/profile/ProfileButton.tsx

This PR addresses an issue reported by a user regarding the discord copy feature in ENS profiles (Issue #550).
**Changes**
The updated code determines whether the social data should be treated as a link or a button
**Testing**
This update has been manually tested with the various of social data types, and also ran the unit tests.

Fix for the Discord Copy Feature in ENS Profiles

---

next.config.js
package.json
pnpm-lock.yaml
src/layouts/Basic.tsx
src/utils/SyncProvider/SyncDroppedTransaction.tsx
src/utils/constants.ts
src/utils/query.ts

chore: add sepolia to supported networks

---

e2e/specs/stateless/wrapName.spec.ts
playwright/fixtures/login.ts
src/components/pages/profile/[name]/tabs/MoreTab/Token/WrapButton.test.tsx
src/components/pages/profile/[name]/tabs/MoreTab/Token/WrapButton.tsx

The wrapName transaction is the only multi step transaction that uses the `getResumable` function. All other transactions are calculated on the fly.

Multi step transactions should not rely on localStorage

---

public/locales/en/common.json
src/components/@molecules/FaucetBanner.tsx
src/hooks/useFaucet.ts
src/utils/constants.ts

changes:
- sepolia added to supported networks for faucet
- faucet messages now use dynamic data (amount, interval) pulled from rpc

feat: sepolia faucet + dynamic faucet data

---

src/components/pages/profile/[name]/tabs/PermissionsTab/NameChangePermissions.tsx

Exception for parent logic when parent is .eth

---

e2e/specs/stateless/profileEditor.spec.ts
e2e/specs/stateless/sendFlow.spec.ts
src/components/pages/profile/[name]/tabs/MoreTab/Resolver.tsx
src/transaction-flow/input/SendName-flow.tsx

Send name default toggle off

---

.vscode/settings.json
src/components/@molecules/ProfileEditor/Avatar/AvatarUpload.test.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarUpload.tsx

changes:
- show error helper if avatar upload fails
- tweaked upload func with better types

show error if avatar upload fails

---

src/components/pages/profile/[name]/tabs/MoreTab/Resolver.tsx

make it clear that resolver edit button is disabled

---

public/locales/en/register.json
src/hooks/useProfileEditor.tsx
src/hooks/useProfileEditorForm.test.ts
src/hooks/useProfileEditorForm.tsx
src/validators/validateAccount.test.ts
src/validators/validateAccount.ts

changes:
- created validateAccount func
- using validateAccount in profile editor form validators
- added error msg for invalid account
- removed old validation code that is no longer used
Fixes FET-1337

validate account value

---

.vscode/settings.json
e2e/specs/stateful/dnsclaim.spec.ts
public/locales/en/dnssec.json
src/components/pages/import/[name]/DNSClaim.tsx
src/utils/query.ts
src/utils/supportLinks.ts

changes:
- removed existing dns import code from main dnsclaim component
- added new content
- added redirect hook for already imported names
- re-added cf sepolia endpoint for ipfs builds (change i made in the dnssec hotfix before) - this fixes ipfs builds
Fixes FET-1358

fix: add dns import maintenance message

---

src/components/TestnetWarning.tsx
src/pages/_app.tsx

show testnet banner when using Goerli / Sepolia

---

src/components/@molecules/ProfileEditor/Avatar/AvatarNFT.test.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarNFT.tsx

fix: use worker proxy for nft endpoint

---

public/locales/en/transactionFlow.json
src/components/@molecules/ProfileEditor/Avatar/AvatarNFT.test.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarNFT.tsx

changes:
- set inner dialog overflow to hidden to avoid overflowing dialog
- added loading state/animation for NFT image
- added error state for NFT image
- removed ability to select nft if it's image wasn't loaded

fix: nft modal behaviour

---

src/components/@molecules/TransactionDialogManager/TransactionDialogManager.tsx

This causes an infinite loading spinner in various situations.

remove input wrapper

---

src/utils/query/wagmi.ts

previously if connecting to a chain other than mainnet, once disconnected, the app would stay stuck on the chain instead of switching back to the default.
Fixes FET-1414

fix: sticky chain id

---

src/components/@atoms/NameDetailItem/NameDetailItem.tsx
src/components/@molecules/AvatarWithLink/AvatarWithLink.tsx
src/components/@molecules/SearchInput/SearchResult.tsx
src/components/AvatarWithZorb.tsx
src/components/ConnectButton.tsx
src/components/NFTWithPlaceholder.tsx
src/components/TabBar.tsx
src/components/pages/profile/ProfileButton.tsx
src/components/pages/profile/ProfileDetails.tsx
src/transaction-flow/input/AdvancedEditor/AdvancedEditor.test.tsx
src/transaction-flow/input/ExtendNames/ExtendNames-flow.tsx
src/transaction-flow/input/ProfileEditor/WrappedAvatarButton.tsx
src/transaction-flow/intro/WrapName.tsx
src/utils/contenthash.ts
src/utils/query/ipfsGateway.ts
src/validators/validateContentHash.test.ts

Also use cf-ipfs.com for IPFS websites so they render properly

Use ENS IPFS gateway

---

src/hooks/dns/useDnsSecEnabled.ts
src/transaction-flow/input/AdvancedEditor/AdvancedEditor-flow.tsx

fix: advanced editor reset

---

src/transaction-flow/input/ExtendNames/ExtendNames-flow.tsx

fix: extend modal layout shift

---

src/components/@atoms/NameDetailItem/NameDetailItem.tsx
src/components/@molecules/ProfileEditor/Avatar/AvatarUpload.tsx
src/components/AvatarWithZorb.tsx
src/components/ProfileSnippet.tsx
src/utils/SyncProvider/SyncProvider.tsx

fix: avatar load

---

src/components/@atoms/NameDetailItem/TaggedNameItem.test.tsx
src/components/@atoms/NameDetailItem/TaggedNameItem.tsx

fix: owner tags in names list

---

src/components/@molecules/AvatarWithLink/AvatarWithLink.tsx

fix: avatar on settings page

---

src/hooks/transactions/waitForTransaction.ts

fix: safe hash tracking

---

package.json
pnpm-lock.yaml
src/components/@molecules/NameListView/NameListView.tsx

chore: bump ensjs + address-encoder

---

src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx

fix: dont allow cached data in tx req

---

src/components/pages/profile/[name]/registration/types.ts
src/hooks/useRegistrationReducer.ts

Prevents existing local storage data items from being used when updates to registration data items are made

add version number to registration reducer data item

---

src/components/pages/import/[name]/shared.tsx

changes:
- fixed alignment of dnssec flow buttons
Fixes FET-1442

fix: dnssec button positions

---

src/layouts/Basic.tsx

changes:
- separated out router nav and switch chain calls
- added shouldSwitchChain func
- only returns true if a request isn't already pending, and there is no error
- has `hasProgrammaticChainSwitching` check because occasionally the request could fire off before the switchChain function on the connector actually existed
Fixes FET-1440

fix: chain switch logic

---

README.md
e2e/specs/stateless/wrapName.spec.ts
package.json
pnpm-lock.yaml
src/utils/query/persist.ts
src/utils/query/reactQuery.ts

See: https://tanstack.com/query/v4/docs/framework/react/plugins/persistQueryClient#building-a-persister

Use indexedDb instead of localStorage for react query cache

---

e2e/specs/stateless/registerName.spec.ts
public/locales/en/register.json
src/components/pages/profile/[name]/registration/steps/Transactions.tsx

changes:
- timer text now specifies 24 hour commit maximum
- timer text now centred
Fixes FET-1541

fix: commit time text

---

scripts/generate-site-map.mjs

now using decentralised graph endpoint + api key

fix: generate sitemap script

---

package.json
pnpm-lock.yaml

| Dependency  | Previous version | New version |
|-------------|------------------|-------------|
| @wagmi/core | 2.10.6           | 2.13.3      |
| viem        | 2.13.8           | 2.19.0      |
| wagmi       | 2.9.11           | 2.12.14     |
Fixes FET-1597

chore: bump viem + wagmi

---

src/hooks/ensjs/public/useRecords.ts

Fix fluidkey address refresh

---

src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx
src/hooks/useQueryOptions.ts

Clearer naming and ts-pattern

---

next-i18next.config.js
public/locales/pt/address.json
public/locales/pt/common.json
public/locales/pt/dnssec.json
public/locales/pt/ensv2.json
public/locales/pt/error.json
public/locales/pt/names.json
public/locales/pt/profile.json
public/locales/pt/register.json
public/locales/pt/settings.json
public/locales/pt/transactionFlow.json
src/i18n.ts

This adds the brazilian portuguese translation to the ENS dapp.

Portuguese Translation

---

e2e/specs/stateless/settings.spec.ts
playwright/pageObjects/settingsPage.ts
src/components/pages/profile/settings/WalletSection.tsx
src/pages/my/settings.tsx

wallet section

---

.claude/settings.local.json
.github/workflows/test.yaml
CLAUDE.md
deploy/00_register_desynced.ts
deploy/00_register_legacy.ts
deploy/00_register_wrapped.ts
deploy/01_sync_time.ts
e2e/specs/stateless/desyncedName.spec.ts
public/locales/en/common.json
public/locales/en/profile.json
src/components/@atoms/BannerMessageWithAction/BannerMessageWithAction.tsx
src/components/@molecules/DesyncedMessage/DesyncedMessage.tsx
src/components/@molecules/SearchInput/SearchResult.tsx
src/components/pages/profile/[name]/Profile.tsx
src/components/pages/profile/[name]/tabs/OwnershipTab/sections/ExpirySection/hooks/useExpiryDetails.ts
src/hooks/nameType/getNameType.ts
src/hooks/ownership/useRoles/utils/getRoles.ts
src/hooks/useNameDetails.test.ts
src/hooks/useNameDetails.tsx
src/transaction-flow/input/ExtendNames/ExtendNames-flow.tsx
src/transaction-flow/input/SendName/utils/checkCanSend.ts
src/transaction-flow/input/SyncManager/utils/checkCanSyncManager.ts
src/transaction-flow/transaction/index.ts
src/transaction-flow/transaction/repairDesyncedName.ts
src/utils/registrationStatus.ts

Summary
This PR implements a comprehensive fix for desynced wrapped names - ENS names where the registry expiry and wrapper expiry are out of sync,
typically caused by renewal through the old ETH registrar controller.
Key Changes
1. Test Infrastructure
- Added deployment script deploy/00_register_desynced.ts to create test desynced names
- Created E2E test suite e2e/specs/stateless/desyncedName.spec.ts to verify repair functionality
- Updated time synchronization in deployment scripts
2. Name Type System Enhancement
- Extended NameType enum to include eth-desynced-2ld and eth-desynced-2ld:grace-period
- Updated getNameType function to detect desynced names based on registry vs wrapper expiry mismatch
- Added desynced status to search results and registration status logic
3. Profile Page …

Bug: fix desynced names
