ensdomains/ens-app-v3

- src/utils/getSocialData.ts
Love the new app!
Users who write their `com.twitter` entry with leading "@" will see "@@" in the UI.
Enhance display logic to ensure the "@" symbol always appears exactly once in the UI.
Patched authored by cory.eth (Cory Gabrielsen) (@cory_eth).
> Gracefully display com.twitter when leading "@"

- src/hooks/useValidate.ts
- previously, URI encoded names were not decoded before being normalised. this would display them as invalid
- now the names are decoded before being normalised
> Fix uri encoded names

- src/components/Header.tsx
- src/components/pages/profile/[name]/details/SubnamesTab.tsx
- src/pages/faq/[slug].tsx
- src/transaction-flow/input/SendName-flow.tsx
- src/transaction-flow/intro/ChangePrimaryName.tsx
- src/transaction-flow/intro/MigrateAndUpdateResolver.tsx
- src/transaction-flow/intro/WrapName.tsx
- removed duplicate FAQ links in navigation
- tweaked styling to increase space between FAQs
- made FAQs clickable to create hyperlinks
- added `:target` styling for FAQs so the user knows which has been linked
- resolved all learn more links:
- Name ownership (transfer flow, send flow): Point to FAQ "What are Managers and Owners?"
- Primary Name: Point to FAQ "What is a primary ENS name?"
- Subnames (subname flow): Point to FAQ "What is the difference between a name and a subname?"
- Resolver upgrade (resolver upgrade flow) Point to FAQ "What is a Resolver?"
- Name wrapper (wrap name flow): Point to FAQ "What is the Name Wrapper?"
> feat: learn more links

- src/transaction-flow/transaction/extendNames.ts
- src/transaction-flow/transaction/migrateProfileWithSync.ts
previously all contenthash utils were bundled into the app via the migrateProfileWithSync transaction.
now within the transaction it is dynamically imported so it can be avoided on first load
> fix: dynamic load contenthash utils in transactions

- src/components/@molecules/AddRecordButton/AddRecordButton.test.tsx
- src/components/@molecules/AddRecordButton/AddRecordButton.tsx
previously when using the profile editor, keys entered in the other tab were not converted to a form safe key before being added to the form. this meant that keys with a dot in them would be incorrectly parsed as a separate group, which would then be shown to the user as "[object Object]"
example:
now before a key is added to the form, it is converted to a form safe value which allows the key to include dots
> fix: other field values in profile editor

- src/components/pages/profile/[name]/Profile.tsx
- src/hooks/useRouterWithHistory.ts
previously would redirect to `/profile/:name` instead of `/:name`
fixed by using getDestination in router.replace
> fix: /my/profile redirect

- src/components/pages/profile/[name]/registration/steps/Profile/AddProfileRecordView.test.tsx
- src/components/pages/profile/[name]/registration/steps/Profile/AddProfileRecordView.tsx
- src/components/pages/profile/[name]/registration/steps/Profile/Profile.tsx
ref: FET-1006
go to edit a profile of a name you own and when adding a new profile record, you should now see a close button in the dialog footer, but no top right dismiss button (cross icon)
> fix: add back button to record input

- src/components/@atoms/NameDetailItem/NameDetailItem.test.tsx
- src/components/@atoms/NameDetailItem/NameDetailItem.tsx
- src/components/@atoms/OptionalLink/OptionalLink.tsx
- src/components/pages/profile/[name]/Profile.tsx
- src/components/pages/profile/[name]/tabs/MoreTab/Ownership.tsx
- src/hooks/useQueryParameterState.ts
the `from` query as well as some other queries that are meant to be hidden from the user are sometimes visible in the browser's url bar. not only does it look ugly, but it also can lead to unexpected behaviour if a user copies a link with hidden queries (such as the back button showing when there is no previous history on the site).
- when replacing the url, `useQueryParameterState` now uses separate `url` and `visibleUrl` objects for corresponding search params.
- profile tabs now use `useQueryParameterState`
- added `BaseLinkWithHistory` to be used in more places so back button is available more consistently (mobile only)
> fix: from in url

- src/components/pages/profile/settings/PrimarySection.tsx
- src/components/pages/profile/settings/TransactionSection.test.tsx
- src/components/pages/profile/settings/TransactionSection.tsx
- src/hooks/useDebouncedCallback.ts
- src/hooks/useThrottledCallback.ts
Latest Update
* Updated the "No primary name set" to match the "No recent transactions" style
Update Outlink red styling
* Go to settings
* Create a failed transaction
* Etherscan link should be red
Transaction List items
* If there is no continue button, do not render container div
* Add padding and remove set height restrictions
> Fix transactions section in settings

- src/components/pages/profile/[name]/tabs/MoreTab/MoreTab.test.tsx
- src/components/pages/profile/[name]/tabs/MoreTab/MoreTab.tsx
this fix is significantly more simple than i thought it would be lol
registrar expiry is now the default expiry, with the wrapper expiry being the fallback
ref: FET-1049
> fix: correct expiry in more tab

- src/components/@molecules/NameTableHeader/NameTableHeader.tsx
- src/components/pages/my/names/MyNames.test.tsx
- src/components/pages/my/names/MyNames.tsx
- src/hooks/useNamesFromAddress.test.ts
- src/hooks/useNamesFromAddress.ts
- src/pages/address.tsx
changes:
- expiry sorting is now correct. previously it was inconsistent when sorting by ascending order.
- set the default value of expiry to be infinity instead of 0
- more technically correct
- means that expiring names will show first when sorting by ascending expiryDate order, rather than names with no expiry
- set ascending as default for sorting
- made the ascending button the left button
Fixes FET-1046 and FET-931
> fix: names table tweaks

- deploy/00_register_legacy.ts
- public/locales/en/common.json
- src/components/@atoms/ExpiryComponents/ExpiryComponents.test.tsx
- src/components/@atoms/ExpiryComponents/ExpiryComponents.tsx
previously we used the end of the grace period as the "real" expiry date in the name detail item (for 2ld .eths)
this meant that messaging regarding the expiry was inconsistent. 
this pr adds a new message specifically for when a name is in grace period, and uses normal expiry terminology for 2ld .eths before the grace period.
e.g.:
- expires in 97 days (grey) -> expires in 7 days (orange)
- expires in 7 days (orange) -> grace period ends in 7 days (red)
> feat: grace period message in name item

- e2e/specs/stateless/07_profileEditor.spec.js
- e2e/specs/stateless/12_updateResolver.spec.js
- src/components/@molecules/DogFood.tsx
- src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.test.tsx
- src/components/@molecules/TransactionDialogManager/stage/TransactionStageModal.tsx
- src/components/Notifications.tsx
- src/hooks/useHasSubnames.ts
- src/hooks/usePrimary.ts
- src/hooks/useProfile.ts
- src/hooks/useResolverStatus.ts
- src/hooks/useSubnameInfiniteQuery.ts
- src/transaction-flow/input/ProfileEditor/ProfileEditor-flow.tsx
- src/utils/SyncProvider.tsx
previously, any `getSubname` query was reset once a graph sync happened. 
the reset is used for `useSubnameInfiniteQuery()` to reset the page and all page data, but the `useHasSubnames()` query also has `getSubnames` in the query key and thus also gets reset.
the reset was not only useless for `useHasSubnames()` but it would also occasionally trigger *after* the query was invalidated, meaning it would reset the newly fetched data, and would not refetch.
changes:
- removed query reset from `Notifications.tsx` as it is already elsewhere and provides the same functionality
- added `graph` to the query key of both `useHasSubnames()` and `useSubnameInfiniteQuery()` to refetch
- added `infinite` to the query reset call in `SyncProvider` so that `useHasSubnames()` is not included
- invalidate …
> fix: fix caching issues

- e2e/specs/stateless/08_registerName.spec.js
- package.json
- src/components/pages/profile/[name]/registration/Registration.tsx
- src/hooks/useBasicName.ts
- src/pages/profile.tsx
Source of issue is that the registrationData is cleared when the router changes. In situations where changing routes takes time, the screen will flash to the registration pricing page since it has no data. Solution is to change the event to cleanup on complete.
> Page flashes registration page when clicking "view name" in Complete.tsx

- src/components/@molecules/SearchInput/SearchInput.test.tsx
- src/components/@molecules/SearchInput/SearchInput.tsx
- src/components/@molecules/SearchInput/SearchResult.test.tsx
- src/components/@molecules/SearchInput/SearchResult.tsx
- src/components/ProfileSnippet.test.tsx
after previous changes with validation logic in the search input, address searches became "invalid" because they were no longer covered under the same `isValid` variable. also, address items did not have pointer cursor set.
changes:
- added logic for the component to not show error state if `inputIsAddress` is true
- added `$clickable` prop to address items for pointer cursor
Fixes FET-1093
> fix: address showing as invalid in search

- src/components/pages/my/names/MyNames.tsx
- src/components/pages/profile/[name]/registration/steps/Pricing/Pricing.tsx
- src/pages/profile.tsx
- src/pages/register.tsx
- src/utils/EnsProvider.test.tsx
- src/utils/EnsProvider.tsx
changes:
- removed `isConnecting` and `isReconnecting` as variables to consider for page loading on profile/registration
- on registration page, set `reverseRecord` checked based on `started` variable in registration data so that it can change on connection
- hide `<PaymentChoice />` on registration page until connected
Fixes FET-1097
> fix: various issues related to connection

- pnpm-lock.yaml
- src/components/pages/profile/[name]/tabs/WrapperCallToAction.test.tsx
- src/components/pages/profile/[name]/tabs/WrapperCallToAction.tsx
changes:
- check if current resolver is namewrapper aware resolver, and only add migrateProfile to transaction stack if this is false
Fixes FET-1122
> fix: check for namewrapper aware resolver when wrapping name

- sentry.client.config.js
sentry replay is currently unused and adds 60kb to bundle size
> fix: disable unused sentry replay

- e2e/specs/stateless/08_registerName.spec.js
- src/components/@atoms/Invoice/Invoice.tsx
- src/components/pages/profile/[name]/registration/FullInvoice.tsx
- src/components/pages/profile/[name]/registration/steps/Info.tsx
- src/components/pages/profile/[name]/registration/steps/Pricing/Pricing.tsx
- src/components/pages/profile/[name]/registration/steps/Transactions.tsx
- src/components/pages/profile/[name]/registration/types.ts
- src/hooks/useEstimateRegistration.ts
- src/hooks/useEstimateTransactionCost.ts
- src/hooks/useRegistrationParams.test.ts
- src/hooks/useRegistrationParams.ts
changes:
- added to `useEstimateRegistration()` hook so that it gets the gas estimate from tenderly via a cloudflare worker
- changed hardcoded gas estimate for registration to be fallback for tenderly estimate (if there is an error)
- set base gas cost for estimate to include a resolver value (since we dont allow unsetting the resolver)
- moved registration param creator into its own hook `useRegistrationParams()`
- added skeleton to gas estimate/total value in invoice for loading instead of displaying an empty div
Fixes FET-1101
> feat: tenderly registration gas estimates

- src/pages/_document.tsx
chrome prefetches and renders pages when searching for urls. if a site is fast enough to load and render before the user visits the page metamask can inject `window.ethereum`, but with messaging setup between the prerendered page and metamask's controller. this means that once the real tab exists, the connections between the page and metamask are killed and rpc requests will be unresponsive.
to fix:
- check for `document.hidden` (on initial load, the likelihood is that this is from prerendering)
- add one time listener for visibilityChange event
- once visibility changes, check for existence of `window.ethereum`
- if `window.ethereum` exists, reload the page
the reload isn't actually visible to the user, the behaviour just mimics that of no prerendering
> fix: metamask connection weirdness from page prefetch

- scripts/generate-site-map.mjs
sub-sitemap paths were incorrectly being written as `/sitemap-[i].xml` when they are actually at `/sitemaps/sitemap-[i].xml`
> fix: add subpath for sitemaps

- package.json
- pnpm-lock.yaml
- src/hooks/useProfile.ts
* Increased network latency time on useProfile from 5000 to 10000 to account for extra time needed to fetch ccip name records
* make getSubnames fails gracefully when the graph has no data for the domain
> Fix subgraph errors showing on ccip names

- src/layouts/Basic.tsx
previously, the iPadOS safari fix was outdated for the current layout padding
changes:
- removed padding reference for iPadOS, now using single variable and css `calc()` instead
- clarified fix for iOS/iPadOS safari
Fixes FET-1026
> fix: ipad layout

- package.json
- pnpm-lock.yaml
changes:
- bumped ens-test-env version (which sets graph-node version to v0.30.0)
- added package.json script for setting subgraph addresses
Fixes FET-1252
> chore: update graph-node version

- src/components/pages/my/names/MyNames.tsx
changes:
- disable all non .eth 2lds when extending names in list (previously could extend any with expiryDate set)
Fixes FET-1275
> fix: disable non .eth 2lds from being extended (for now)

- src/components/ProfileSnippet.tsx
- src/components/pages/profile/[name]/tabs/MoreTab/Miscellaneous/ExtendButton.tsx
- src/components/pages/profile/[name]/tabs/ProfileTab.tsx
- src/hooks/abilities/useAbilities.ts
- src/utils/abilities/shouldShowExtendWarning.test.ts
- src/utils/abilities/shouldShowExtendWarning.ts
previously, in certain situations when extending a name, it could show the ownership warning even when the user was the owner.
changes:
- added check function for showing warning
- checks edit OR send ability
- use check function in profile snippet + more tab
Fixes FET-1268
> fix: extend warning not showing when user is owner but not manager

- src/components/pages/profile/[name]/registration/Registration.tsx
- src/components/pages/profile/[name]/registration/types.ts
- src/components/pages/profile/[name]/registration/useMoonpayRegistration.ts
- src/hooks/useRegistrationReducer.ts
- src/pages/register.tsx
previously, when registering a name on a testnet and switching to mainnet, the registration status wouldn't change since it didn't use chainId as a unique identifier. in practice, when someone registered a name on testnet and got to the success step, when switching to mainnet it would still show the success page instead of going back to the start of registration.
changes:
- added chainId as a selected item identifier for registration-status reducer
> fix: add chainid identifier to registration-status

- .vscode/settings.json
changes:
- typescript tsdk changed to use node_modules
- eslint node path removed (not required)
- prettier path changed to use node_modules
> chore: vscode config tweaks

- e2e/specs/stateless/advancedEditor.spec.ts
- e2e/specs/stateless/profileEditor.spec.ts
- playwright/pageObjects/advancedEditorModal.ts
- playwright/pageObjects/index.ts
- playwright/pageObjects/recordsPage.ts
- playwright/pageObjects/transactionModal.ts
- src/components/@molecules/AdvancedEditor/AdvancedEditorTabContent.tsx
- src/components/RecordItem.tsx
- src/components/pages/profile/[name]/tabs/RecordsTab.tsx
- src/hooks/useAdvancedEditor.test.ts
- src/hooks/useAdvancedEditor.ts
- src/hooks/useExpandableRecordsGroup.ts
- src/transaction-flow/input/AdvancedEditor/AdvancedEditor.test.tsx
- src/utils/records.ts
**Changes**
1. Fix deletion of non-evm records for advanced records editor: Fixed api for deleting address record from empty address (0x0) to  empty string ('')
2. Fix the rebuild state process when the "back" button is pressed in the transaction modal.
3. Fixed the display items to show changes to the Abi.
> fix/advanced editor: abi, rebuilding state, delete addresses

- src/pages/unsupportedNetwork.tsx
changes:
- update supported chain ids for unsupportedNetwork page rerouting
- update "Change network" button on unsupportedNetwork page to prompt a switch to mainnet (was goerli)
repro steps:
1. be on a supported network in metamask (e.g. mainnet)
2. connect to the ens app
3. switch to unsupported network (e.g. base, linea)
4. if you weren't automatically directed to `/unsupportedNetwork`, go to `/unsupportedNetwork`
5. click the "Change network" button
6. you will be prompted to switch to goerli
> hotfix: mainnet for unsupported network change button

- src/components/pages/import/[name]/utils.ts
changes:
- removed unused `isSubdomainSet`
- `isDnsSecEnabled` now checks for NXDOMAIN before checking for DNSSEC validity, this fixes the intended behaviour of the func
Fixes FET-1310
> fix: dnssec check

- .gitignore
- src/components/pages/import/[name]/AddTextRecord.tsx
- src/components/pages/import/[name]/DNSClaim.tsx
- src/components/pages/import/[name]/EnableDNSSEC.tsx
- src/hooks/dns/useDnsSecEnabled.ts
- src/hooks/ensjs/dns/useDnsOwner.ts
- src/hooks/useSupportsTLD.ts
The work flow of dns import had some flashing issues and difficulty navigating back and forth. Fixed the navigation and well as improved by reusing common hooks that were used in multiple "views"
> fix dns import to use common hooks and fix step flow

- src/components/@molecules/SearchInput/SearchInput.tsx
- src/components/pages/profile/[name]/Profile.tsx
- src/hooks/useBasicName.ts
- src/hooks/useNameDetails.tsx
- src/hooks/useProfile.ts
- src/utils/registrationStatus.test.ts
- src/utils/registrationStatus.ts
changes:
- no longer fetching resolver data for registration status calc
- any ccip-read dns name with an eth address will show as imported, instead of just gasless dnssec
- no longer requiring is2LD to be true to fetch addr for dns name
- gasless subname imports will show as imported
- made batch return into obj
> fix: show all dns names with eth record as imported at a minimum

- src/components/@molecules/AvatarWithIdentifier/AvatarWithIdentifier.tsx
- src/components/@molecules/ProfileEditor/Avatar/AvatarUpload.tsx
- src/components/pages/profile/[name]/registration/useMoonpayRegistration.ts
- src/routes.ts
- src/utils/utils.ts
the `#` character is supported by name normalisation when used for the #️⃣ emoji. previously, this was an issue because although nextjs router automatically URI encodes all path data, `#` is seen to signify a browser location, so is not encoded, and breaks decoding the name in the app.
changes:
- `getDestination()` now manually rewrites `#` to `%23`, which covers all cases where a name is used in nextjs router.
this is not a permanent fix. i'll rewrite the routing system to accommodate this in the viem branch.
Fixes FET-1375
> (hot)fix: support for # sign in app

- src/components/Outlink.tsx
- src/components/pages/profile/[name]/Profile.tsx
- src/layouts/Content.tsx
- src/pages/address.tsx
Profile page:
it also hides an icon if no address was set
Address page:
> add etherscan icon to profile and address pages

- src/pages/404.tsx
nextjs adds spacing comments when rendering, which can lead to issues with the title element having multiple children where it should just have 1. (see https://github.com/vercel/next.js/discussions/38256)
changes:
- wrapped 404 page title in string literal to ensure the content output is flat
Fixes FET-1413
> fix: title array error

- src/components/@molecules/NameListView/NameListView.tsx
set `resolvedAddress` param to be false
> fix: resolved address names in names page

- src/hooks/useProfileActions.ts
- src/utils/checkAvailablePrimaryName.test.ts
Previously profile's isMigrated was either null | boolean, with off chain names it is undefined. Need to update condition as checking for !== false
> fix for offchain names checkAvailablePrimaryName

- src/components/pages/import/[name]/DnsClaim.tsx
changes:
- added logic for redirecting away from dns claim page if a name is already claimed
- does not redirect away if the flow needs to be completed first, similar to registration
- added useBasicName call to `<DnsClaim />`
- this kinda sucks because its only required in the redirect logic but its not already called in a parent or anything
Fixes FET-1441
> fix: add dnsclaim redirect for claimed names

- e2e/specs/stateless/setPrimary.spec.ts
- src/utils/checkAvailablePrimaryName.test.ts
- src/utils/checkAvailablePrimaryName.ts
changes:
- removed `registrant` check in `isResolvedOrManagedName`, because matching registrant relation does not imply that the name is resolved or managed by the connected account.
- added unit test for case
Fixes FET-1446
> fix: remove primary name flow if manager transfer is required

- src/hooks/useBasicName.test.ts
- src/hooks/useBasicName.ts
`commonEnabled` was set to false when `isShort` is true, but that value is not based on `isETH` being true, when it was expected to be. changed the conditional to be `!(isETH && isShort)`
> fix: useOwner enabled case

- src/components/@molecules/SearchInput/SearchInput.tsx
- src/hooks/useBasicName.ts
- src/utils/registrationStatus.ts
Bug: Entering [root] in search input causes app to crash
Cause: [root] breaks namehash because of invalid characters but [root] is an accepted input.
Fix: Remove [root] for other search item lists so that it does not attempt to namehash name
Other fix:  getRegistrationStatus, return 'owned' in name is [root]
Small fix: Adding key attribute through spread operator throws a warning in React 18
> Fix [root] search in input

- src/components/pages/profile/[name]/registration/steps/Transactions.tsx
Core issue is that *useSimulateContract* will continue to run even when *enabled* is switched to false.
Fix is to add another condition (transaction.status !== 'complete') to canRegisterOverride variable.
> FET1672: Registration override message

- e2e/specs/stateless/verifications.spec.ts
- src/hooks/verification/useDentityProfile/useDentityProfile.ts
- src/hooks/verification/useDentityToken/useDentityToken.ts
- src/hooks/verification/useVerificationOAuth/utils/getAPIEndpointForVerifier.ts
- src/hooks/verification/useVerificationOAuthHandler/useVerificationOAuthHandler.ts
- src/hooks/verification/useVerificationOAuthHandler/utils/createVerificationTransactionFlow.ts
- src/hooks/verification/useVerificationOAuthHandler/utils/dentityHandler.ts
When processing the *code* received from dentity.com when returning from their site, the manager app would fail because the app would refresh, causing a refetch of the name info which is one time use only.
FIX:
Split the processing of the code into two hooks:
1. useDentityToken - Is only responsible for the name info from dentity.com. This has a **staleTime** of _Infinity_ and a **queryDependencyType** of _independent_.  This was necessary because the former **queryDependencyType** of _standard_ injects the user's address into the **queryKey**, triggering a refetch when the page is reloaded.
2. useDentityProfile - Processes the dentity token and adds additional information such as the owner, manager, resolver address and current verification uri.
To test the implementation, in the e2e …
> Fix enter verification process from unconnected state

- e2e/specs/stateless/extendNames.spec.ts
- src/components/@molecules/TransactionDialogManager/DisplayItems.tsx
- src/transaction-flow/transaction/extendNames.test.ts
- src/transaction-flow/transaction/extendNames.ts
- src/types/index.ts
> Extend names duration fix

- src/components/pages/profile/[name]/registration/steps/Transactions.tsx
- src/hooks/registration/useCheckRegistered.ts
- src/transaction-flow/utils/shouldSkipTransactionUpdateDuringTest.ts
TLDR
Support has reported  an issue where the manager displays an error on the register name step even though the name has finished registration and the user owns the name.
The likely cause is a race condition that is somehow getting the flow stuck and displaying the error for registering an already registered name.
FIX
When register name transaction is sent, begin polling to detect if the user is the owner of the name. If the owner matches the user, force push the Registration Complete view.
HOW TO TEST
Should use dev environment on sepolia or holesky.  This is because the local development anvil chain does not support running useSimulation and the preview may not have the flag that triggers the development flag that will prevent the transactions from updating.
Use the prefix …
> Add forced completion in registration flow if app detects name is registered

- e2e/specs/stateless/wrapName.spec.ts
- src/hooks/useBasicName.ts
- test/mock/makeMockUseBasicName.ts
Unwrapped names should not show wrap name button in other tab.
Will also need to check:
* Shows the button for unwrapped subnames
*. Shows the button for unwrapped onchain imported names/subnames
* Does not show button for off chain names/subnames
* Does not show button for eth (old)
> Fix: Names in grace period should not show wrap button

- package.json
When testing safe transactions QA needs to alter chains.ts in order to set the chain to a testate. This adds a vulnerability for them to commit the change. Adding script so that they don't need to do this.
> Add scripts for https test nets

- e2e/specs/stateless/wrapName.spec.ts
- src/components/@molecules/TransactionDialogManager/stage/query.ts
- src/constants/chains.ts
- src/utils/query/wagmi.ts
- src/utils/utils.ts
adds explicit transaction type for MetaMask transactions to avoid this issue: https://github.com/MetaMask/core/issues/5720
only added on MetaMask txs in case explicit type is an issue in any wallets
> fix: metamask explicit transaction type

- functions/_middleware.ts
fixes #608 
safari is similar to firefox in that we can remove all but `frame-ancestors` from the CSP header, and utilise the CSP meta tag
> fix: safari csp

- src/hooks/chain/useEstimateGasWithStateOverride.ts
- src/hooks/gasEstimation/calculateTransactions.ts
- src/hooks/gasEstimation/useEstimateRegistration.ts
- src/utils/constants.ts
previously when a user was disconnected, in place of their address for estimating gas for transactions, we'd use `0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266` - a standard test address derived from `test test test test test test test test test test test junk`.
EIP-7702 was recently launched on mainnet, which allows a user to delegate the functionality of their address to a contract. someone delegated the test address to a sweeper contract, but that sweeper contract doesn't implement `onERC1155Received`, so the registration transaction reverts.
changes:
- set disconnected placeholder account to `0x0000000000000000000000000000000000001234`, an address no one has the private key for
- also massively increased the override balance to 1,000,000 ETH to ensure gas can still be estimated for names …
> fix: disconnected gas estimates

- src/constants/chains.ts
- src/constants/resolverAddressData.test.ts
For Holesky and Sepolia, the latest registrar controller has some configuration issues so we rolled them back to a previous version by overriding the contracts on the chain
> Issues when interacting with primary name on Sepolia/Holesky

- e2e/specs/stateful/profile.spec.ts
Updated the stateful test so that it no longer fails
1. Replaced temporary premium name with active name
2. Hid the profile check on the profile dropdown as that wallet doesn't have a primary name. Unable to set primary name on holesky due to error restrictions, will bring them back once able to set primary name/swapping to Sepolia.
> Fix failing stateful test due to temp premium name

- src/components/@atoms/NameDetailItem/NameDetailItem.tsx
- src/components/AvatarWithZorb.tsx
in https://github.com/ensdomains/thorin/commit/7fd8153b0d8b4e11ee23de216a4a64ccc2b3a4db the `<Avatar />` component changed from using the CSS `background` property for an avatar placeholder, to using `src` (on `<img />`). 
with this change, the app is no longer using the zorb as a placeholder, instead it is firing a broken request which 404s every time. zorbs still show up in most cases, because when an avatar record is not available, the zorb value is used for the `src` parameter. however in the case that a broken but valid avatar record is used, a broken image placeholder is used which looks completely out of place. example name: https://sepolia.app.ens.domains/swagalicious.eth
changes:
- removed css URL formatting for placeholders
- removed background colour on avatar to avoid alias …
> fix: placeholder zorb in avatar
